[program:higgs_sglang]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/higgs-sglang.sh
autostart=true
autorestart=unexpected
startsecs=10
stdout_logfile=/var/log/portal/higgs_sglang.log
redirect_stderr=true
stdout_logfile_maxbytes=0
