[program:higgs_api]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/higgs-api.sh
autostart=true
autorestart=unexpected
startsecs=3
stdout_logfile=/var/log/portal/higgs_api.log
redirect_stderr=true
stdout_logfile_maxbytes=0
